using System;
using System.Runtime.Serialization;

namespace Microsoft.ReportingServices.Diagnostics.Utilities
{
	// Token: 0x02000075 RID: 117
	[Serializable]
	internal sealed class ModelNotAutoGeneratedException : ReportCatalogException
	{
		// Token: 0x06000221 RID: 545 RVA: 0x00004ABC File Offset: 0x00002CBC
		public ModelNotAutoGeneratedException(string modelPath)
			: base(ErrorCode.rsModelNotGenerated, ErrorStringsWrapper.rsModelNotGenerated, null, null, Array.Empty<object>())
		{
		}

		// Token: 0x06000222 RID: 546 RVA: 0x00004AD2 File Offset: 0x00002CD2
		private ModelNotAutoGeneratedException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
		}
	}
}
