using System;

namespace Microsoft.InfoNav.Explore.ExploreConverter.Internal
{
	// Token: 0x020000B3 RID: 179
	internal sealed class SortExpression
	{
		// Token: 0x060003D2 RID: 978 RVA: 0x000141C8 File Offset: 0x000123C8
		internal SortExpression(Expression value, bool autoGenerated, SortDirection direction)
		{
			this._value = value;
			this._autoGenerated = autoGenerated;
			this._direction = direction;
		}

		// Token: 0x17000139 RID: 313
		// (get) Token: 0x060003D3 RID: 979 RVA: 0x000141E5 File Offset: 0x000123E5
		internal Expression Value
		{
			get
			{
				return this._value;
			}
		}

		// Token: 0x1700013A RID: 314
		// (get) Token: 0x060003D4 RID: 980 RVA: 0x000141ED File Offset: 0x000123ED
		internal bool AutoGenerated
		{
			get
			{
				return this._autoGenerated;
			}
		}

		// Token: 0x1700013B RID: 315
		// (get) Token: 0x060003D5 RID: 981 RVA: 0x000141F5 File Offset: 0x000123F5
		internal SortDirection Direction
		{
			get
			{
				return this._direction;
			}
		}

		// Token: 0x0400024B RID: 587
		private readonly Expression _value;

		// Token: 0x0400024C RID: 588
		private readonly bool _autoGenerated;

		// Token: 0x0400024D RID: 589
		private readonly SortDirection _direction;
	}
}
