using System;
using System.Collections.Generic;
using Microsoft.BIServer.HostingEnvironment.HostingInfo;

namespace Microsoft.PowerBI.ReportServer.WebApi.FeatureSwitches
{
	// Token: 0x02000034 RID: 52
	internal static class PbiFeatureSwitches
	{
		// Token: 0x060000F7 RID: 247 RVA: 0x000049A4 File Offset: 0x00002BA4
		static PbiFeatureSwitches()
		{
			Dictionary<string, bool> dictionary = new Dictionary<string, bool>
			{
				{ "approvedResourcesDisabled", false },
				{ "scriptVisualEnabled", true },
				{ "rScriptVisualEnabled", false },
				{ "customVisualsTenantEnabled", true },
				{ "forceMigrateNewFilterPane", true },
				{ "crossReportDrill", false },
				{ "enableNewFilterOnAllReports", true },
				{ "visualInsights", false },
				{ "esriVisualEnabled", true },
				{ "blankCanvasWatermark", true },
				{ "tenantOutOfBoxVisualsEnabled", false },
				{ "manageMarketplaceVisuals", false },
				{ "rdlNativeVisual", false }
			};
			dictionary["customVisuals"] = HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnableCustomVisuals, false);
			dictionary["approvedResourcesDisabled"] = !HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnableCDNVisuals, false);
			dictionary["exportDataEnabled"] = HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnablePowerBIReportExportData, false);
			dictionary["exportToExcelSettingEnabled"] = HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnablePowerBIReportExportData, false);
			dictionary["exportToCsvEnabled"] = HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnablePowerBIReportExportData, false);
			dictionary["exportUnderlyingDataEnabled"] = HostingState.Current.IsConfigSwitchEnabled(ConfigSwitches.EnablePowerBIReportExportUnderlyingData, false);
			PbiFeatureSwitches._clientSwitches = PbiFeatureSwitches.OverlayFromLeftToRight(new IReadOnlyDictionary<string, bool>[]
			{
				PbiFeatureSwitches.DefaultClientSwitches(),
				dictionary
			});
			Dictionary<string, bool> dictionary2 = new Dictionary<string, bool>();
			PbiFeatureSwitches._serverSwitches = PbiFeatureSwitches.OverlayFromLeftToRight(new IReadOnlyDictionary<string, bool>[]
			{
				PbiFeatureSwitches.DefaultServerSwitches(),
				dictionary2
			});
		}

		// Token: 0x060000F8 RID: 248 RVA: 0x00004B24 File Offset: 0x00002D24
		public static IReadOnlyDictionary<string, bool> OverlayFromLeftToRight(params IReadOnlyDictionary<string, bool>[] switches)
		{
			Dictionary<string, bool> dictionary = new Dictionary<string, bool>();
			foreach (IReadOnlyDictionary<string, bool> readOnlyDictionary in switches)
			{
				foreach (string text in readOnlyDictionary.Keys)
				{
					dictionary[text] = readOnlyDictionary[text];
				}
			}
			return dictionary;
		}

		// Token: 0x17000045 RID: 69
		// (get) Token: 0x060000F9 RID: 249 RVA: 0x00004B9C File Offset: 0x00002D9C
		public static IReadOnlyDictionary<string, bool> ClientSwitches
		{
			get
			{
				return PbiFeatureSwitches._clientSwitches;
			}
		}

		// Token: 0x17000046 RID: 70
		// (get) Token: 0x060000FA RID: 250 RVA: 0x00004BA3 File Offset: 0x00002DA3
		public static IReadOnlyDictionary<string, bool> ServerSwitches
		{
			get
			{
				return PbiFeatureSwitches._serverSwitches;
			}
		}

		// Token: 0x060000FB RID: 251 RVA: 0x00004BAC File Offset: 0x00002DAC
		private static IReadOnlyDictionary<string, bool> DefaultClientSwitches()
		{
			return new Dictionary<string, bool>
			{
				{ "a11yMatrix", true },
				{ "a11yShowAsMatrix", true },
				{ "a11yTable", true },
				{ "additionalKPISettings", true },
				{ "addPreviewTagToAttachExternalDataflow", true },
				{ "adlsBasedModelTakeover", true },
				{ "adminAuditingEnabled", true },
				{ "adminBranding", true },
				{ "adminCapacityEnabled", true },
				{ "AdminCustomDisclaimerUI", true },
				{ "adminDataProtection", true },
				{ "advancedSlicerSyncing", true },
				{ "aiInsightsFunctionBrowser", true },
				{ "allowContributorUpdateApp", true },
				{ "allowEmailSecurityGroupsOnOutage", true },
				{ "allowExploreDatasetOfApp", true },
				{ "allowFreeUsersToSubscribeInPremiumAppsUI", true },
				{ "allowGatewayForRDLWithCloudDS", true },
				{ "allowReshareDatasetOfApp", true },
				{ "allowSubscribeOthersWithRLS", true },
				{ "allowSubscribingOnlyExternalUsers", true },
				{ "allowTenantAdminDisableWorkspaceV1Creation", true },
				{ "allUpSaveReport", true },
				{ "almConsumerInfoVisibility", true },
				{ "altTextForVisual", true },
				{ "analyticsRibbon", true },
				{ "analyzeInExcelEnabled", true },
				{ "analyzeInExcelOdcFallbackUI", true },
				{ "analyzeInExcelSovereignFormatEnabled", true },
				{ "annotationsUI", true },
				{ "anomalyDetection", true },
				{ "anonymousEmbeddingEnabled", true },
				{ "appAccessRequestUI", true },
				{ "appEmailSubscription", true },
				{ "applyAllSlicersButton", true },
				{ "appNavGA", true },
				{ "appsEnabled", true },
				{ "appThemingUI", true },
				{ "areaChartTransparency", true },
				{ "artifactDescriptionsUI", true },
				{ "artifactSearchUI", true },
				{ "AsyncExploreClientFlows", true },
				{ "AutoMlModelAuthoring", true },
				{ "axisInteractivity", true },
				{ "azureMapVisual", true },
				{ "baseTheme", true },
				{ "baseThemeUpdate", true },
				{ "blankCanvasWatermark", true },
				{ "bookmarkGrouping", true },
				{ "bookmarkNavigatorSeparate", true },
				{ "breadcrumbNavigationEnabled", true },
				{ "buttonTileFormatting", true },
				{ "byoResourcesStorageAccountUI", true },
				{ "byoResourcesUI", true },
				{ "canvasItemsPane", true },
				{ "capacitiesAzureTab", true },
				{ "capacitiesMigrateSpecificWorkspaces", true },
				{ "capacitiesVcores", true },
				{ "capacityBanner", true },
				{ "capacityGen2Create", true },
				{ "capacityGen2Toggle", true },
				{ "capacityMetricDrilldown", true },
				{ "capacityRestartButton", true },
				{ "capacitySettingsTabs", true },
				{ "capacityWorkloadMemoryControls", true },
				{ "capacityWorkloads", true },
				{ "cartesianConditionalFormatting", true },
				{ "cartesianExtStylesColumn", true },
				{ "cartesianExtStylesColumn2", true },
				{ "cartesianMultiplesAccessibility", true },
				{ "cartesianMultiplesAuthoring", true },
				{ "cartesianMultiplesGridFormatting", true },
				{ "cartesianMultiplesGridPadding", true },
				{ "categoricalDynamicFormatting", true },
				{ "categoricalSecondaryCF", true },
				{ "cdsaBringYourOwnStorageAccountUI", true },
				{ "cdsaCDMFolderReferenceUI", true },
				{ "cdsaEntitiesRelationships", true },
				{ "cdsaExperimentalConnectors", true },
				{ "cdsaExternalStorageReferenceUI", true },
				{ "cdsaFastCombineDefaultOffFrontend", true },
				{ "cdsaFolderStorageAccountUI", true },
				{ "cdsaFrontend", true },
				{ "cdsaGranularSQLUI", true },
				{ "cdsaSendEmailOnRefreshFailureUI", true },
				{ "cdsaSettingsTakeover", true },
				{ "CdsaStorageAccountDetachUI", true },
				{ "cdsaStorageUpdateMissingParamsUI", true },
				{ "certifyDatasetsSetting", true },
				{ "changeDetection", true },
				{ "clientUsageMetricsEnabled", true },
				{ "closeAccountEnabled", true },
				{ "cloudRlsImpersonationEnabled", true },
				{ "cloudRlsRoleMembershipEnabled", true },
				{ "commonDataServiceSSO", true },
				{ "comparisonODataPredicates", true },
				{ "conditionalFormattingDataLabels", true },
				{ "conditionalTablixWebURL", true },
				{ "configureAppContacts", true },
				{ "consumePublicCvsWithoutRps", true },
				{ "contactsSettingsList", true },
				{ "contentListNew", true },
				{ "copyRdlReportToWorkspaceV2", true },
				{ "copyReportsToWorkspacesV2", true },
				{ "copyVisualImage", true },
				{ "createAppWorkspaceSettingMigration", true },
				{ "createCapacityWithRegion", true },
				{ "csvContentProviderEnabled", true },
				{ "customCommands", true },
				{ "customFormatStrings", false },
				{ "customVisuals", true },
				{ "customVisualsEndpointV2", true },
				{ "customVisualsGallery", true },
				{ "customVisualsStore", true },
				{ "customVisualsTenantSwitch", true },
				{ "customVisualsUseStaticSandbox", true },
				{ "d3v5", true },
				{ "dashboardB2BSharingWithRegularHost", true },
				{ "dashboardEmailSubscription", true },
				{ "dashboardEmbedEnabled", true },
				{ "dashboardThemesUI", true },
				{ "dataBarsUpdate", true },
				{ "dataBoundPropertiesUseThemeDefaults", false },
				{ "databricksSSO", true },
				{ "dataClassificationEnabled", true },
				{ "dataPointLassoSelect", true },
				{ "datasetDownloadPbix", true },
				{ "datasetPropertiesSection", true },
				{ "dataSourceVariablesOverride", true },
				{ "dataSourceVariablesOverrideShared", true },
				{ "dataViewTargeted", true },
				{ "dateODataType", true },
				{ "datetimeMinMaxSupported", true },
				{ "decompositionTree", true },
				{ "decompositionTreeConditionalFormat", true },
				{ "decompositionTreeCoreVisual", true },
				{ "decompositionTreeCrossHighlight", true },
				{ "decompositionTreeResponsiveLayout", true },
				{ "decompTreeBarsPerLevel", true },
				{ "decompTreeTooltipMeasure", true },
				{ "defaultSortMethodology", true },
				{ "defaultTooltipFormatting", true },
				{ "deleteSharedDatasetUi", true },
				{ "deprecateArchivedContent", true },
				{ "devToolsNewVisual", true },
				{ "devToolsVisualSettings", true },
				{ "directQueryScheduledRefresh", true },
				{ "directToMwc", true },
				{ "disableExportDataOnVisualError", true },
				{ "disablePublishToWebCreation", true },
				{ "discussInTeams", true },
				{ "discussInTeamsForDashboard", true },
				{ "downloadReportEnabled", true },
				{ "drillFilterOtherVisuals", true },
				{ "drillthroughButtonGA", true },
				{ "drillthroughText", true },
				{ "dsrV2", true },
				{ "dynamicMessageEnabled", true },
				{ "easierHierarchicalAxis", true },
				{ "eimInformationProtectionLicenseEnforcementUI", false },
				{ "eimInformationProtectionRemoveViewSwitchUI", true },
				{ "eimInformationProtectionUI", true },
				{ "elevatedGuests", true },
				{ "emailSubscriptionEnabled", true },
				{ "emailSubscriptionTenantAdminSettings", true },
				{ "emailSubscriptionV2", true },
				{ "embedFullFidelityWorkbooks", true },
				{ "embedUseModernExplorationContainer", true },
				{ "emCVBundle", true },
				{ "enableBIU", true },
				{ "enableExportDataNewDialog", true },
				{ "enterpriseGatewayEnabled", true },
				{ "enterpriseGatewayETLEnabled", true },
				{ "errorBarsGA", true },
				{ "esriEnabled", true },
				{ "excelWorkbooksInContentPackEnabled", true },
				{ "explanationsReport", false },
				{ "exportDataMode", true },
				{ "exportExcelExcludeMeasures", true },
				{ "ExportHostErrorList", true },
				{ "exportPbixForGeneratedModelsUI", true },
				{ "exportReportToPdfEnabled", true },
				{ "exportReportToPowerPointEnabled", true },
				{ "exportVisualToExcelEnabled", true },
				{ "exprBoundActions", true },
				{ "exprBoundAltText", true },
				{ "exprBoundBorderColor", true },
				{ "exprBoundColors", true },
				{ "exprBoundColorValidation", true },
				{ "exprBoundGaugeColors", true },
				{ "exprBoundVisualTitle", true },
				{ "expressionBasedFormatting", true },
				{ "externalConnectorSSO", true },
				{ "favoritesEnabled", true },
				{ "ffxlChartSelectionEnabled", true },
				{ "ffxlLocalFilesEnabled", true },
				{ "fieldAlias", true },
				{ "fileExportPolling", true },
				{ "fillPointStyle", true },
				{ "filteredFavoriteFrequent", true },
				{ "flipStackOrder", true },
				{ "fluentListUI", true },
				{ "fluentTopLevelList", true },
				{ "forceCapacityFolderAlmPipeline", true },
				{ "forceMigrateNewFilterPane", true },
				{ "fraSubscriptionsUI", true },
				{ "freeTrialTenantSetting", true },
				{ "fullFidelityExcelEnabled", true },
				{ "gatewayMultipleCredentials", true },
				{ "gatewayMultipleCredentialsRDLReports", true },
				{ "gatewayUXImprovements", true },
				{ "gaugeConditionalFormatting", true },
				{ "granularExternalSharingControl", true },
				{ "granularTenantControls", true },
				{ "groupCapacity", true },
				{ "handleErrorOnQueryDataAPIThrottling", true },
				{ "helpAndSupportSettings", true },
				{ "hideReportVerticalPane", true },
				{ "hideWorkspacesWidget", true },
				{ "hierarchicalSlicer", true },
				{ "hierarchicalSlicerCreation", true },
				{ "homeBannerText", true },
				{ "homeDashboardEnabled", true },
				{ "homeGettingStartedPbixSample", true },
				{ "homeIsAngularOnly", true },
				{ "homeLayoutTabList", true },
				{ "homeRecommendedAppsUI", true },
				{ "homeUI", true },
				{ "htmlLegend", true },
				{ "httpServiceModern", true },
				{ "importJsonModel", true },
				{ "importPbiviz", true },
				{ "increasedExportSectionLimit", true },
				{ "inlineExplore", true },
				{ "inODataPredicates", true },
				{ "InsightApps", true },
				{ "InsightsContinuationTokens", true },
				{ "insightsContinuationTokensUX", true },
				{ "insightsPane", true },
				{ "insightsStoreEnabled", true },
				{ "insightsSyncEndpoint", true },
				{ "instantEmail", true },
				{ "instantEmailSubscriptionV2", true },
				{ "interactivityServiceOptimization", true },
				{ "invitationHostDeprecation", true },
				{ "keepQueryProjOrderForShowAll", true },
				{ "kerberosDqRefresh", true },
				{ "keyboardShortcutsLassoSelect", true },
				{ "keyDriverPaas", true },
				{ "keyDrivers", true },
				{ "keyDriversCounting", true },
				{ "keyDriversDetails", true },
				{ "keyDriversVisualColor", true },
				{ "labelEnhancementsM0", true },
				{ "lazyAngularJSInfra", true },
				{ "lazyLoadLandingContainer", true },
				{ "lessIntrusiveNpsDialog", true },
				{ "lineageViewUsageMetrics", true },
				{ "lineChartLabelPosition", true },
				{ "lineChartSeriesLabels", true },
				{ "lineExtStyles", true },
				{ "lineMarkersEnabled", true },
				{ "linkToPowerAutomateExportTemplate", true },
				{ "listViewEnabled", true },
				{ "loadBaseTheme", true },
				{ "manageLicensesControl", true },
				{ "manageMarketplaceVisuals", true },
				{ "mapPointSampling", true },
				{ "matrixLayouts", true },
				{ "matrixWordWrap", true },
				{ "measureDrivenDataLabels", true },
				{ "mobileAuthoringFormattingUI", true },
				{ "modelingServiceGenerateModel", true },
				{ "modernDashboard", true },
				{ "modernDatasetDialog", true },
				{ "modernFolderService", true },
				{ "modernPackageRefreshListener", true },
				{ "modernWebReportLoad", true },
				{ "monthlySubscriptions", true },
				{ "moveSlicerTypeSelection", true },
				{ "multipleODataPredicates", true },
				{ "multiRowCardSelection", true },
				{ "narrativeTextbox", true },
				{ "navAndDrillthroughActionTypes", true },
				{ "navBarNew", true },
				{ "navigatorTogglePage", true },
				{ "navigatorVisuals", true },
				{ "navigatorAccentBar", true },
				{ "navPaneNew", true },
				{ "newDSCompInDataset", true },
				{ "newFieldList", true },
				{ "newLookAdminSettingUI", true },
				{ "newLookForAll", true },
				{ "newLookUI", true },
				{ "newResizeSensor", true },
				{ "newUsageMetrics", true },
				{ "newVisualLegendPositions", true },
				{ "noEmptyUpdate", true },
				{ "nonAsciiODataNames", true },
				{ "northStarBreadcrumb", true },
				{ "numericSlicerEnabled", true },
				{ "o365LauncherV2", true },
				{ "oneGBUploadFileSizeEnabled", true },
				{ "onPremDirectQuerySingleSignOnForOracle", true },
				{ "onPremDirectQuerySingleSignOnForSAP", true },
				{ "onPremDirectQuerySingleSignOnForSapBw", true },
				{ "onPremDirectQuerySingleSignOnForSapBwMessageServer", true },
				{ "onPremDirectQuerySingleSignOnForSql", true },
				{ "onPremDirectQuerySingleSignOnForTeradata", true },
				{ "openExploreErrorDetails", true },
				{ "optimizedAppMetadataForHome", true },
				{ "optimizedAppMetadataForReportLanding", true },
				{ "optimizePublishToWeb", true },
				{ "orgAppsEnabled", true },
				{ "outlineDropdownToCheckboxes", true },
				{ "outspaceBackground", true },
				{ "paasDynamicRoutingEnabled", true },
				{ "paginatedReports", true },
				{ "paginatedReportsSqlAzureSSO", true },
				{ "paginatedReportsSubscriptions", true },
				{ "pbiRSKey", true },
				{ "perfInspector", true },
				{ "permissionCenterEnabled", true },
				{ "personalBookmarksNewUI", true },
				{ "personalBookmarksUI", true },
				{ "personalizeVisualsPerspectives", true },
				{ "personalVisualizationPaneEnabled", true },
				{ "pieChartMarginBetweenSlices", true },
				{ "pipelines", true },
				{ "pivotTableVisualEnabled", true },
				{ "playAxisDataColors", true },
				{ "ppuTenantSettings", true },
				{ "previewConceptualModel", true },
				{ "promotedContentUI", true },
				{ "propertyEvaluationWarnings", true },
				{ "qnaDashboardEditable", true },
				{ "qnaExport", true },
				{ "qnaThumbsUpDown", true },
				{ "qnaVisual", true },
				{ "queryApplicationContext", true },
				{ "queryCancellation", true },
				{ "quickCreate", true },
				{ "quickExplore", true },
				{ "rdlAnaheimWebApp", true },
				{ "rdlGenerateLinkUI", true },
				{ "rdlPaginatedView", true },
				{ "rdlReportAnaheim", true },
				{ "rdlReportAnnotationsUI", true },
				{ "rdlReportInApps", true },
				{ "RdlReportInGlobalSearch", true },
				{ "rdlReportJsonRplRenderer", true },
				{ "rdlReportPrint", true },
				{ "rdlReportSharingUI", true },
				{ "rdlSecureEmbed", true },
				{ "readOnlyGroupEnabled", true },
				{ "realTimeRefresh", true },
				{ "rebindReportUi", true },
				{ "recentNew", true },
				{ "redlineAlignment", true },
				{ "refreshCenterHistory", true },
				{ "refreshCenterTimetable", true },
				{ "remainingCartesianCategoryLogAxisScale", true },
				{ "removeAuthoringToolSaveButton", true },
				{ "removeDataflowPreviewTag", true },
				{ "removeDefaultToCircleToggle", true },
				{ "removeScaleDetector", true },
				{ "reportAnnotationsUI", true },
				{ "reportEmbedUpdateHostDataEnabled", false },
				{ "reportFavoritesUI", true },
				{ "reportMeasures", true },
				{ "reportPagePanePositionSetting", true },
				{ "reportSharingUI", true },
				{ "responsiveCartesianChart", true },
				{ "responsiveSlicer", true },
				{ "rolloutCapacitiesList", true },
				{ "saasMarketplace", true },
				{ "salesforceAndOneDriveCredentialsEnabled", true },
				{ "sandboxVisualsEnabled", true },
				{ "scatterWithDataVolume", true },
				{ "scatterWithMatrixDV", true },
				{ "scatterXYGrouping", true },
				{ "scheduledRefreshCCNotifications", true },
				{ "scheduledSubscriptionUI", true },
				{ "scopedAggregates", true },
				{ "scopedDataBoundExprs", true },
				{ "searchWorkspaces", true },
				{ "securePublishToWeb", true },
				{ "selfServicePurchase", true },
				{ "sendLocalDatesForSubscription", true },
				{ "serviceAppsEnabled", true },
				{ "servicePrincipalTenantAdminSettings", true },
				{ "shapeFormattingFeatures", true },
				{ "shapeVisual", true },
				{ "sharedDataflowDiscoveryUI", true },
				{ "sharedDatasetDiscovery", true },
				{ "sharePointDocumentLibrariesEnabled", true },
				{ "sharePointEmbedEnabled", true },
				{ "showChatForNewUsers", true },
				{ "showDataflowsInGetData", true },
				{ "showDefaultTooltip", true },
				{ "showNewMarketplaceAppsUx", true },
				{ "singleFilterPane", true },
				{ "SinglePageExports", true },
				{ "slicerAccessibility", true },
				{ "slicerSyncing", true },
				{ "slowDataSourceModeEnabled", true },
				{ "smallMultiplesConditionalFormatting", true },
				{ "smallMultiplesResponsive", true },
				{ "smallMultiplesSortByMeasure", true },
				{ "smallMultiplesSubheaderFormatting", true },
				{ "smallMultiplesUnsharedAxes", true },
				{ "socialSharingEnabled", true },
				{ "sortLegend", true },
				{ "sparkAppEnabled", true },
				{ "splitGrandTotals", true },
				{ "splitHelpTooltip", true },
				{ "splitSubTotals", true },
				{ "spoIntegration", true },
				{ "stackedTotalDataLabels", true },
				{ "stagingRdlInApps", true },
				{ "stickyUserStateCustomViz", true },
				{ "stickyUserStateUI", true },
				{ "stickyUserStateUIThrottling", true },
				{ "stringMinMax", true },
				{ "strokeExtStyles", true },
				{ "subscribeExternalUsers", true },
				{ "subscribeOthersUI", true },
				{ "subscriptionOptionalPreviewImage", true },
				{ "suppressDefaultTooltip", true },
				{ "switchAxisPosition", true },
				{ "tableMultiSort", true },
				{ "tablixCellCopy", true },
				{ "tablixIcons", true },
				{ "tablixImageWidth", true },
				{ "tablixPreserveScrollFix", true },
				{ "tablixTotalLabel", true },
				{ "tablixWordWrap", true },
				{ "tealTheme", true },
				{ "tenantOutOfBoxVisualsEnabled", true },
				{ "tenGBUploadFileSizeEnabled", true },
				{ "textboxSuperSubScriptBulletedList", true },
				{ "themeRelative", true },
				{ "themeTextStyles", true },
				{ "tileMenu", true },
				{ "totalsConditionalFormatting", true },
				{ "trackUserInfo", true },
				{ "umv2Upgrade", true },
				{ "unreadAnnotationsBadge", true },
				{ "updateFormattingPaneObjects", true },
				{ "upgradeOutlineProperties", true },
				{ "urlBookmarksUI", true },
				{ "usageMetricsPackageCleanup", true },
				{ "usageMetricsRetroactiveDisable", true },
				{ "usageMetricsUpgrade", true },
				{ "useBatchGeocoding", true },
				{ "useHttp2QueryData", true },
				{ "useHttp2QueryDataForAsAzure", true },
				{ "useModernDatePickerSlicer", true },
				{ "useModernExplorationContainer", true },
				{ "useModernExploreCanvas", true },
				{ "useModernFooter", true },
				{ "useModernFormatPane", true },
				{ "useModernLicenseHelperService", true },
				{ "useModernLicenseStrategyService", true },
				{ "useModernPromiseFactory", true },
				{ "useModernVisual", true },
				{ "useModernVisualTypesContainer", true },
				{ "useNewCY19SU06BaseTheme", true },
				{ "userFavoriteResourcePackagesEnabled", true },
				{ "userNotificationsEnabled", true },
				{ "userStateBookmarkImprovements", false },
				{ "useVisualModern", true },
				{ "vcPadding", true },
				{ "visualContainerLassoSelect", true },
				{ "visualDropShadow", true },
				{ "visualInsights", true },
				{ "visualLevelSlicerFilters", true },
				{ "visualsOutsideNgZone", true },
				{ "waterfallTotals", true },
				{ "webNavigationMigration", true },
				{ "whatIf", true },
				{ "workloadMetrics", true },
				{ "workspacesV2", true },
				{ "workspacesV2Downgrade", true },
				{ "workspacesV2GA", true },
				{ "workspacesV2GAFeatures", true },
				{ "workspacesV2OptInUpgrade", true },
				{ "workspacesV2OptInUpgradeButton", true },
				{ "workspacesV2UnifiedGroups", true },
				{ "workspacesV2UsageMetrics", true },
				{ "workspacesV2ViewerRole", true },
				{ "xAxisRefLineImprovements", true },
				{ "yellowIntegrationOfPowerBI", true },
				{ "zOrder", true }
			};
		}

		// Token: 0x060000FC RID: 252 RVA: 0x000062E8 File Offset: 0x000044E8
		private static IReadOnlyDictionary<string, bool> DefaultServerSwitches()
		{
			return new Dictionary<string, bool>
			{
				{ "AccessSecondaryDBServer", true },
				{ "AdjustedDirectQueryInterval", true },
				{ "AdvancedAnalyticsDynamicCPUAffinity", true },
				{ "AIEAppTokenAuthPaginatedReports", true },
				{ "AllowMultipleCredsForDatasource", true },
				{ "AllUpSaveReport", true },
				{ "AnalyticsAnomalyDetectionTransform", true },
				{ "AnalyticsForecast", true },
				{ "AnalyticsNLGTransforms", true },
				{ "AnalyticsSamplingTransform", true },
				{ "AnnaTalkConversation", true },
				{ "AnonymousEmbeddingService", true },
				{ "AppEmailSubscription", true },
				{ "AppModel", true },
				{ "AS_SSPA_SkipCertificateCheck", false },
				{ "Auditing", true },
				{ "AutoAddDeprovisionRecordFromDisabledTenantDetection", true },
				{ "AzureEmailService", true },
				{ "BISitesIWTrialSignUp", true },
				{ "BISitesLegacyAPIDeprecation", true },
				{ "BISitesO365TopNav", true },
				{ "BISitesRDLSupport", true },
				{ "BlobCleanupPostTenantDeletion", true },
				{ "CapacityAdminService", true },
				{ "CapacityMigrationTriggerExpansion", true },
				{ "CapacityWorkspaceMigration", true },
				{ "CarbonFlighting", true },
				{ "CheckWebRequestTenantMatch", true },
				{ "CleanupTempDirectory", true },
				{ "CleanupUnusedDatasourcesV1", true },
				{ "ClientTelemetryEndpoint", true },
				{ "CloudRoleLevelSecurity", true },
				{ "CloudRoleLevelSecurityImpersonation", true },
				{ "CloudRoleLevelSecurityMembership", true },
				{ "ContentProviderParameterValidation", true },
				{ "ContentProvidersRecommendation", true },
				{ "CreateASDataset", true },
				{ "CSPDeputyScenario", true },
				{ "CsvContentProvider", true },
				{ "CustomVisualsInOrgContentPacks", true },
				{ "DashboardEmailSubscription", true },
				{ "DashboardEmbedability", true },
				{ "DashboardEmbedabilityAddTile", true },
				{ "DataClassification", true },
				{ "DataDrivenAlert", true },
				{ "DataShapingBatchManagedProcessing", true },
				{ "DataShapingUnifiedRegularProcessing", true },
				{ "DataSourceAppOwnership", false },
				{ "DedicatedCapacity", true },
				{ "DeleteUsingGetArtifactsForOrgAppDeletionSproc", true },
				{ "DeployModelingService", true },
				{ "DeprecateDmtsLongIdApi", true },
				{ "DeprovisioningStoredProcs", true },
				{ "DevApiAppKeyAuth", true },
				{ "DiscoverEGWsForAppPrincipal", true },
				{ "DiscoverMonikerSystemV2", true },
				{ "DiscoverService", true },
				{ "DMTSGatewayVersionSupport", true },
				{ "DMTSKerberosSSOAll", true },
				{ "DMTSMigrationStage1", false },
				{ "DMTSSkipTestConnection", true },
				{ "DMTSUnifiedVersionSupport", true },
				{ "DSEConceptualSchema", false },
				{ "DSEMultiSubqueries", true },
				{ "DSENewSubquery", true },
				{ "DSEOnPremDynamicLimits", true },
				{ "DSEScopedAggregates", true },
				{ "DSESubqueryTransform", true },
				{ "DSETopNPerLevel", true },
				{ "DSRv2", true },
				{ "DynamicPaasRoutingRead", true },
				{ "DynamicPaasRoutingWrite", true },
				{ "EmailSubscription", true },
				{ "EmbeddedReportSnapshots", true },
				{ "EngineActivityTrace", true },
				{ "EsriVisualAdminDefault", true },
				{ "ExcelProviderUseExtendedDataAccessInfo", true },
				{ "ExportPowerPoint", true },
				{ "ExportReportToPbix", true },
				{ "ExportToExcel", true },
				{ "ExtendedDataAccessInfoMigration", true },
				{ "FullFidelityLargeWorkbooks", true },
				{ "FullFidelityLocalFiles", true },
				{ "FullFidelityWorkbooks", true },
				{ "GetArtifactsForOrgAppDeletionSproc", true },
				{ "GetDashboardViaStoredProcedure", true },
				{ "GetMetadataCommonViaStoredProcedure", true },
				{ "GetModelDataTilesWithDataStoredProc", false },
				{ "GetModelTilesWithDataOptimization", true },
				{ "GetVisualContainersOfModelForUsersAsSP", true },
				{ "GlobalAcceptCustomVisuals", true },
				{ "GranularTenantControls", true },
				{ "GWFailFastMechanism", true },
				{ "IncludeSafeASQueryErrorsInDsr", true },
				{ "InfoNavEmbeddability", true },
				{ "InfoNavRuntimeModeling", false },
				{ "InfoNavSamplesOnly", false },
				{ "InfoNavUsageReporting", true },
				{ "InsightServiceCacheConnectionPool", true },
				{ "InsightServiceDeriveInsights", true },
				{ "InsightServiceRuntimeRequestThrottling", true },
				{ "IosPushNotificationOnNewGroupDashboard", true },
				{ "LargeWorkbooksConnect", true },
				{ "LiveConnectionRefreshSchedule", true },
				{ "MashupDirectQuery", true },
				{ "MExtensibilityForPGW", true },
				{ "MicrosoftFlowDataDrivenAlertConnector", true },
				{ "Minerva", true },
				{ "MinervaForcedUpgrade", true },
				{ "ModelResourceKeyAuth", true },
				{ "MParameterColumnMapping", true },
				{ "NearRealTimeAnalytics", true },
				{ "NegatedTuplesFiltering", true },
				{ "NLInternalLanguages", false },
				{ "NLPreviewLanguages", true },
				{ "NLUseExternalServiceOnly", false },
				{ "OnPremDirectQuerySingleSignOn", true },
				{ "OverwriteNonLocalPackageError", true },
				{ "PaasOnPremGateway", true },
				{ "PackageRefreshAutoLock", true },
				{ "PBIXRefresh", true },
				{ "PowerBIAnonymousAccess", false },
				{ "PowerBIClientSideEncryption", true },
				{ "PowerBIContentProviderPublishing", true },
				{ "PowerBICortanaIntegration", false },
				{ "PowerBIDatabaseQueriesThrottler", true },
				{ "PowerBIDataMovementAddDatasourceV2", true },
				{ "PowerBIDataMovementCloudRefresh", true },
				{ "PowerBIDataMovementDiscoverDatasourcesV1", true },
				{ "PowerBIDataMovementDiscoverGatewaysV4", true },
				{ "PowerBIDataMovementDiscoverMonikersByName", true },
				{ "PowerBIDataMovementEL2", true },
				{ "PowerBIDataMovementEL3", true },
				{ "PowerBIDataMovementETL", true },
				{ "PowerBIDataMovementHighAvailability", true },
				{ "PowerBIDataMovementMashupEngineBinding", true },
				{ "PowerBIDataMovementOAuth", true },
				{ "PowerBIDataMovementOAuthReturnAadOption", true },
				{ "PowerBIDatasets", true },
				{ "PowerBIDisableAccount", true },
				{ "PowerBIFeatureManagement", true },
				{ "PowerBIGroupInvite", true },
				{ "PowerBIGroups", true },
				{ "PowerBIImportAPI", true },
				{ "PowerBIImportAPIV1", true },
				{ "PowerBIInvitationReshareEmailValidation", true },
				{ "PowerBIOrganizationalPackaging", true },
				{ "PowerBIPackaging", true },
				{ "PowerBIPersonalGateway", true },
				{ "PowerBIQuota", true },
				{ "PowerBIQuotaEnforcement", false },
				{ "PowerBIServiceMonitor", true },
				{ "PowerBISignUp", false },
				{ "PowerBITakeoverTenant", true },
				{ "PowerBIUsageBilling", true },
				{ "PowerViewDataShapeQueryTranslationBatchQueryPattern", true },
				{ "PowerViewSendFeedback", false },
				{ "PowerViewServerSideLayout", true },
				{ "PowerViewVRMAuthoring", true },
				{ "PowerViewVrmPlayAxis", true },
				{ "PowerViewVRMThumbnails", true },
				{ "PowerViewVrmWebClient", true },
				{ "PublishPbixLiveConnect", true },
				{ "PushDataBetaEndpointRoutingToResta", true },
				{ "PushDataCreateRestaDataset", true },
				{ "PushDataRestaAdvancedModelingPropertiesBeta", true },
				{ "PushDataRestaAdvancedModelingPropertiesV1", true },
				{ "PushNotificationOnSharedDashboard", true },
				{ "PV_HTML5", false },
				{ "QueryApplicationContext", true },
				{ "QueryEditVariables", true },
				{ "QueryExtensionColumns", true },
				{ "QueryNativeExpressions", true },
				{ "QueryRequestPriority", true },
				{ "RealTimeApi", true },
				{ "RefreshDashboardTilesJob", true },
				{ "RefreshModelAfterPackage", true },
				{ "ReportMeasures", true },
				{ "RequestHostNameMatchWithClusterName", true },
				{ "RestaSqlAzureColumnStoreIndex", true },
				{ "RLSDetection", true },
				{ "RowLevelSecurity", true },
				{ "RSGateway_PVHttp_API", true },
				{ "RunDisabledTenantDetection", false },
				{ "SaaSAppAPI", true },
				{ "SaaSDashboardEmbed", true },
				{ "SalesforceReports", true },
				{ "SAPHanaOverV3ExecutionFramework", true },
				{ "ScriptVisual", true },
				{ "ScriptVisualAdminDefault", true },
				{ "SelectiveQueryRefresh", true },
				{ "SelectiveRefreshDisableModelRefresh", true },
				{ "SelectiveRefreshEnableModelRefresh", true },
				{ "SelectiveRefreshTelemetryProcessor", true },
				{ "SelfServicePredictiveAnalytics", false },
				{ "SelfServicePredictiveAnalyticsDT", false },
				{ "SemanticQueryLet", true },
				{ "ServiceBusBasedPackageRefresh", true },
				{ "SetStateManagerMinCpu", true },
				{ "SmallMultiplesPreview", true },
				{ "SRTestConnections", true },
				{ "StaticExportApi", true },
				{ "SuperDaxMD", true },
				{ "SyncServiceV2RedisLists", true },
				{ "TenantUserSync", true },
				{ "TenGBUploadFileSize", true },
				{ "UnifiedGateway", true },
				{ "UnifiedNotification", true },
				{ "UnifiedNotificationAzureHubCarrier", true },
				{ "UpdateInvalidRefreshToken", true },
				{ "UsageMetrics", true },
				{ "UseIdempotentSingletonPrimaryRouter", true },
				{ "UseMashupWrapProvider", true },
				{ "UseMsalForTokenGeneration", true },
				{ "UseNewestCertificatesForTokenEncryptionAndSigning", true },
				{ "UserDataV2BlobETagTracking", true },
				{ "UserDataV2BlobMigration", true },
				{ "UserDataV2Storage", true },
				{ "UseSafePackageStringModifier", true },
				{ "UseV2StorageAccountForModelBackup", true },
				{ "VARole", true },
				{ "VARoleFailover", true },
				{ "WriteWorkspaceCollectionDmtsDatasourceOwnershipMode", true },
				{ "XmlaAadAuthentication", true }
			};
		}

		// Token: 0x040000A1 RID: 161
		private static readonly IReadOnlyDictionary<string, bool> _clientSwitches;

		// Token: 0x040000A2 RID: 162
		private static readonly IReadOnlyDictionary<string, bool> _serverSwitches;
	}
}
