using System;

namespace Microsoft.Lucia.Core
{
	// Token: 0x020000A6 RID: 166
	[Flags]
	public enum InterpretWarnings : long
	{
		// Token: 0x040003A4 RID: 932
		None = 0L,
		// Token: 0x040003A5 RID: 933
		LinguisticSchemaAutoGenerated = 1L,
		// Token: 0x040003A6 RID: 934
		LinguisticSchemaNotAvailable = 2L,
		// Token: 0x040003A7 RID: 935
		LinguisticSchemaIsStillLoading = 4L,
		// Token: 0x040003A8 RID: 936
		DataModelLoadPartiallySuccessful = 8L,
		// Token: 0x040003A9 RID: 937
		InvalidDataModel = 16L,
		// Token: 0x040003AA RID: 938
		DataRetrievalFailed = 32L,
		// Token: 0x040003AB RID: 939
		DataRetrievalSkipped = 64L,
		// Token: 0x040003AC RID: 940
		DuplicateExecuteSemanticQuery = 128L,
		// Token: 0x040003AD RID: 941
		SampleValuesFailed = 256L,
		// Token: 0x040003AE RID: 942
		SchemaLanguageNotSupported = 512L,
		// Token: 0x040003AF RID: 943
		IndexIsBuilding = 1024L,
		// Token: 0x040003B0 RID: 944
		EmptyLinguisticSchema = 2048L,
		// Token: 0x040003B1 RID: 945
		SomeInputSpansNotConsumed = 4096L,
		// Token: 0x040003B2 RID: 946
		MissingOrInvalidPodParameters = 8192L,
		// Token: 0x040003B3 RID: 947
		StaleDataIndex = 16384L,
		// Token: 0x040003B4 RID: 948
		CloudRlsModelAccessDenied = 32768L,
		// Token: 0x040003B5 RID: 949
		UnknownModelError = 65536L,
		// Token: 0x040003B6 RID: 950
		OnPremModelAccessDenied = 131072L,
		// Token: 0x040003B7 RID: 951
		SemanticError = 262144L,
		// Token: 0x040003B8 RID: 952
		SemanticWarning = 524288L,
		// Token: 0x040003B9 RID: 953
		InvalidTextualEntity = 1048576L,
		// Token: 0x040003BA RID: 954
		LinguisticSchemaTruncated = 2097152L,
		// Token: 0x040003BB RID: 955
		DataIndexSizeLimitReached = 4194304L,
		// Token: 0x040003BC RID: 956
		DataIndexMissingStatistics = 8388608L,
		// Token: 0x040003BD RID: 957
		QueryAggregateNotSupported = 16777216L,
		// Token: 0x040003BE RID: 958
		QueryMedianNotSupported = 33554432L,
		// Token: 0x040003BF RID: 959
		QueryScopedEvalNotSupported = 67108864L,
		// Token: 0x040003C0 RID: 960
		QueryPercentileNotSupported = 134217728L,
		// Token: 0x040003C1 RID: 961
		QuerySubqueryRegroupingNotSupported = 268435456L,
		// Token: 0x040003C2 RID: 962
		DataIndexBuildingCancelled = 536870912L,
		// Token: 0x040003C3 RID: 963
		InterpretCancelled = 1073741824L,
		// Token: 0x040003C4 RID: 964
		DataIndexMissingAllStatistics = 2147483648L,
		// Token: 0x040003C5 RID: 965
		QueryNotSupported = 4294967296L,
		// Token: 0x040003C6 RID: 966
		IndexWasClosed = 8589934592L,
		// Token: 0x040003C7 RID: 967
		QueryGroupByTableNotSupported = 17179869184L,
		// Token: 0x040003C8 RID: 968
		NextBestInterpretation = 34359738368L
	}
}
