using System;
using Microsoft.Reporting.QueryDesign.Edm.Internal;
using Microsoft.Reporting.QueryDesign.ExpressionTrees.Internal;

namespace Microsoft.Reporting.QueryDesign.QueryDefinitionModel.Internal
{
	// Token: 0x0200011A RID: 282
	internal sealed class SortItem
	{
		// Token: 0x0600101C RID: 4124 RVA: 0x0002C597 File Offset: 0x0002A797
		internal SortItem(GroupKey groupKey, SortDirection sortDirection = SortDirection.Ascending, QueryExpression sortExpression = null, bool autogenerated = false)
			: this(groupKey.Name, sortDirection, sortExpression, autogenerated)
		{
		}

		// Token: 0x0600101D RID: 4125 RVA: 0x0002C5A9 File Offset: 0x0002A7A9
		internal SortItem(string name, SortDirection sortDirection = SortDirection.Ascending, QueryExpression sortExpression = null, bool autogenerated = false)
		{
			this._name = name;
			this._sortDirection = sortDirection;
			this._sortExpression = sortExpression;
			this._autogenerated = autogenerated;
		}

		// Token: 0x170004D7 RID: 1239
		// (get) Token: 0x0600101E RID: 4126 RVA: 0x0002C5CE File Offset: 0x0002A7CE
		public string Name
		{
			get
			{
				return this._name;
			}
		}

		// Token: 0x170004D8 RID: 1240
		// (get) Token: 0x0600101F RID: 4127 RVA: 0x0002C5D6 File Offset: 0x0002A7D6
		public SortDirection SortDirection
		{
			get
			{
				return this._sortDirection;
			}
		}

		// Token: 0x170004D9 RID: 1241
		// (get) Token: 0x06001020 RID: 4128 RVA: 0x0002C5DE File Offset: 0x0002A7DE
		public bool Autogenerated
		{
			get
			{
				return this._autogenerated;
			}
		}

		// Token: 0x06001021 RID: 4129 RVA: 0x0002C5E6 File Offset: 0x0002A7E6
		public bool RefersTo(INamedItem namedItem)
		{
			return namedItem != null && this.RefersTo(namedItem.Name);
		}

		// Token: 0x06001022 RID: 4130 RVA: 0x0002C5F9 File Offset: 0x0002A7F9
		public bool RefersTo(string candidateName)
		{
			return EdmItem.IdentityComparer.Equals(candidateName, this.Name);
		}

		// Token: 0x06001023 RID: 4131 RVA: 0x0002C60C File Offset: 0x0002A80C
		public bool HasSameExpression(QueryExpression other)
		{
			return (this._sortExpression == null && other == null) || (this._sortExpression != null && this._sortExpression.Equals(other));
		}

		// Token: 0x04000A5D RID: 2653
		private readonly string _name;

		// Token: 0x04000A5E RID: 2654
		private readonly SortDirection _sortDirection;

		// Token: 0x04000A5F RID: 2655
		private readonly QueryExpression _sortExpression;

		// Token: 0x04000A60 RID: 2656
		private readonly bool _autogenerated;
	}
}
