using System;

namespace Microsoft.HostIntegration.DrdaClient
{
	// Token: 0x02000A2B RID: 2603
	internal class DrdaProceduresSchemaQuery : DrdaSchemaQuery
	{
		// Token: 0x0600518F RID: 20879 RVA: 0x0014C968 File Offset: 0x0014AB68
		public DrdaProceduresSchemaQuery()
			: base(new string[] { "PROCEDURE_CAT", "PROCEDURE_SCHEM", "PROCEDURE_NAME", "NUM_INPUT_PARAMS", "NUM_OUTPUT_PARAMS", "NUM_RESULT_SETS", "REMARKS" }, new Type[]
			{
				typeof(string),
				typeof(string),
				typeof(string),
				typeof(int),
				typeof(int),
				typeof(int),
				typeof(string)
			}, new int[] { 0, 1, 2 }, new string[] { null, "ROUTINE_SCHEMA", "ROUTINE_NAME", "IN_PARMS+INOUT_PARMS", "OUT_PARMS+INOUT_PARMS", "RESULT_SETS", "LONG_COMMENT" }, "SYSPROCS", new string[] { null, "OWNER", "NAME", "IN_PARMS", "OUT_PARMS", "RESULT_COLS", "REMARKS" }, "<CustomQuery2>", new string[] { null, "PROCSCHEMA", "PROCNAME", "COUNT_IN", "COUNT_OUT", "RESULT_SETS", "REMARKS" }, "<CustomQuery1>")
		{
		}

		// Token: 0x06005190 RID: 20880 RVA: 0x0014CAD9 File Offset: 0x0014ACD9
		public override string GetMVSTable(string catalog)
		{
			return string.Format("(SELECT PROCS.OWNER, PROCS.NAME, (COALESCE(INPARMS.COUNT_IN,0) + COALESCE(INOUTPARMS.COUNT_INOUT,0)) AS IN_PARMS, (COALESCE(OUTPARMS.COUNT_OUT,0) + COALESCE(INOUTPARMS.COUNT_INOUT,0)) AS OUT_PARMS, PROCS.RESULT_COLS, PROCS.REMARKS FROM {0}.SYSROUTINES AS PROCS FULL OUTER JOIN (SELECT OWNER, NAME, COUNT(*) AS COUNT_IN FROM {0}.SYSPARMS WHERE ROWTYPE = 'P' GROUP BY OWNER, NAME) AS INPARMS ON PROCS.OWNER = INPARMS.OWNER AND PROCS.NAME = INPARMS.NAME FULL OUTER JOIN (SELECT OWNER, NAME, COUNT(*) AS COUNT_OUT FROM {0}.SYSPARMS WHERE ROWTYPE = 'O' GROUP BY OWNER, NAME) AS OUTPARMS ON PROCS.OWNER = OUTPARMS.OWNER AND PROCS.NAME = OUTPARMS.NAME FULL OUTER JOIN (SELECT OWNER, NAME, COUNT(*) AS COUNT_INOUT FROM {0}.SYSPARMS WHERE ROWTYPE = 'B' GROUP BY OWNER, NAME) AS INOUTPARMS ON PROCS.OWNER = INOUTPARMS.OWNER AND PROCS.NAME = INOUTPARMS.NAME) AS TBL", catalog);
		}

		// Token: 0x06005191 RID: 20881 RVA: 0x0014CAE6 File Offset: 0x0014ACE6
		public override string GetUDBTable(string catalog)
		{
			return string.Format("(SELECT PROCS.PROCSCHEMA, PROCS.PROCNAME, COALESCE(INPARMS.COUNT_IN,0) AS COUNT_IN, COALESCE(OUTPARMS.COUNT_OUT,0) AS COUNT_OUT,  PROCS.RESULT_SETS, PROCS.REMARKS  FROM {0}.PROCEDURES AS PROCS FULL OUTER JOIN (SELECT PROCSCHEMA, PROCNAME, COUNT(*) AS COUNT_IN FROM {0}.PROCPARMS WHERE PARM_MODE LIKE '%%IN%%' GROUP BY PROCSCHEMA, PROCNAME) AS INPARMS ON PROCS.PROCSCHEMA = INPARMS.PROCSCHEMA AND PROCS.PROCNAME = INPARMS.PROCNAME FULL OUTER JOIN (SELECT PROCSCHEMA, PROCNAME, COUNT(*) AS COUNT_OUT FROM {0}.PROCPARMS WHERE PARM_MODE LIKE '%%OUT%%' GROUP BY PROCSCHEMA, PROCNAME) AS OUTPARMS ON PROCS.PROCSCHEMA = OUTPARMS.PROCSCHEMA AND PROCS.PROCNAME = OUTPARMS.PROCNAME) AS TBL", catalog);
		}
	}
}
