using System;
using System.Data;
using System.Data.Common;
using Microsoft.HostIntegration.Drda.Requester;

namespace Microsoft.HostIntegration.DrdaClient
{
	// Token: 0x02000A25 RID: 2597
	internal class DrdaReservedWordsInformation
	{
		// Token: 0x170013B0 RID: 5040
		// (get) Token: 0x06005172 RID: 20850 RVA: 0x00149072 File Offset: 0x00147272
		public static string SchemaName
		{
			get
			{
				return DbMetaDataCollectionNames.ReservedWords;
			}
		}

		// Token: 0x06005173 RID: 20851 RVA: 0x0014907C File Offset: 0x0014727C
		public static DataTable Execute(DrdaConnection conn)
		{
			DataTable dataTable = new DataTable(DrdaReservedWordsInformation.SchemaName);
			dataTable.Columns.Add(DbMetaDataColumnNames.ReservedWord, typeof(string));
			HostType hostType = DrdaSchemaQuery.GetHostType(conn);
			if (hostType != HostType.AS400)
			{
				if (hostType != HostType.NT)
				{
					for (int i = 0; i < DrdaReservedWordsInformation.ReservedWordsHOSTDB2.Length; i++)
					{
						DataRow dataRow = dataTable.NewRow();
						dataRow[DbMetaDataColumnNames.ReservedWord] = DrdaReservedWordsInformation.ReservedWordsHOSTDB2[i];
						dataTable.Rows.Add(dataRow);
						dataRow.AcceptChanges();
					}
				}
				else
				{
					for (int j = 0; j < DrdaReservedWordsInformation.ReservedWordsUDB.Length; j++)
					{
						DataRow dataRow = dataTable.NewRow();
						dataRow[DbMetaDataColumnNames.ReservedWord] = DrdaReservedWordsInformation.ReservedWordsUDB[j];
						dataTable.Rows.Add(dataRow);
						dataRow.AcceptChanges();
					}
				}
			}
			else
			{
				for (int k = 0; k < DrdaReservedWordsInformation.ReservedWordsAS400.Length; k++)
				{
					DataRow dataRow = dataTable.NewRow();
					dataRow[DbMetaDataColumnNames.ReservedWord] = DrdaReservedWordsInformation.ReservedWordsAS400[k];
					dataTable.Rows.Add(dataRow);
					dataRow.AcceptChanges();
				}
			}
			return dataTable;
		}

		// Token: 0x04004028 RID: 16424
		private static string[] ReservedWordsHOSTDB2 = new string[]
		{
			"ADD", "AFTER", "ALL", "ALLOCATE", "ALLOW", "ALTER", "AND", "ANY", "AS", "ASENSITIVE",
			"ASSOCIATE", "ASUTIME", "AT", "AUDIT", "AUX", "AUXILIARY", "BEFORE", "BEGIN", "BETWEEN", "BUFFERPOOL",
			"BY", "CALL", "CAPTURE", "CASCADED", "CASE", "CAST", "CCSID", "CHAR", "CHARACTER", "CHECK",
			"CLONE", "CLOSE", "CLUSTER", "COLLECTION", "COLLID", "COLUMN", "COMMENT", "COMMIT", "CONCAT", "CONDITION",
			"CONNECT", "CONNECTION", "CONSTRAINT", "CONTAINS", "CONTENT", "CONTINUE", "CREATE", "CURRENT", "CURRENT_DATE", "CURRENT_LC_CTYPE",
			"CURRENT_PATH", "CURRENT_SCHEMA", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURSOR", "DATA", "DATABASE", "DAY", "DAYS", "DBINFO",
			"DECLARE", "DEFAULT", "DELETE", "DESCRIPTOR", "DETERMINISTIC", "DISABLE", "DISALLOW", "DISTINCT", "DO", "DOCUMENT",
			"DOUBLE", "DROP", "DSSIZE", "DYNAMIC", "EDITPROC", "ELSE", "ELSEIF", "ENCODING", "ENCRYPTIONEND", "ENDINGEND-EXEC",
			"ERASE", "ESCAPE", "EXCEPT", "EXCEPTION", "EXECUTE", "EXISTS", "EXIT", "EXPLAIN", "EXTERNAL", "FENCED",
			"FETCH", "FIELDPROC", "FINAL", "FOR", "FREE", "FROM", "FULL", "FUNCTION", "GENERATED", "GET",
			"GLOBAL", "GO", "GOTO", "GRANT", "GROUP", "HANDLER", "HAVING", "HOLD", "HOUR", "HOURS",
			"IF", "IMMEDIATE", "IN", "INCLUSIVE", "INDEX", "INF", "INFINITY", "INHERIT", "INNER", "INOUT",
			"INSENSITIVE", "INSERT", "INTERSECT", "INTO", "IS", "ISOBID", "ITERATE", "JAR", "JOIN", "KEEP",
			"KEY", "LABEL", "LANGUAGE", "LC_TYPE", "LEAVE", "LEFT", "LIKE", "LOCAL", "LOCALE", "LOCATOR",
			"LOCATORS", "LOCK", "LOCKMAX", "LOCKSIZE", "LONG", "LOOP", "MAINTAINED", "MATERIALIZED", "MICROSECOND", "MICROSECONDS",
			"MINUTE", "MINUTES", "MODIFIES", "MONTH", "MONTHS", "NAN", "NEXTVAL", "NO", "NOT", "NULL",
			"NULLS", "NUMPARTS", "OBID", "OF", "ON", "OPEN", "OPTIMIZATION", "OPTIMIZE", "OR", "ORDER",
			"OUT", "OUTER", "PACKAGE", "PADDED", "PARAMETER", "PART", "PARTITION", "PARTITIONED", "PARTITIONING", "PATH",
			"PIECESIZE", "PLAN", "PRECISION", "PREPARE", "PREVVAL", "PRIQTY", "PRIVILEGES", "PROCEDURE", "PROGRAM", "PSID",
			"PUBLIC", "QUERY", "QUERYNO", "READS", "REFERENCES", "REFRESH", "RELEASE", "RENAME", "REPEAT", "RESIGNAL",
			"RESTRICT", "RESULT", "RESULT_SET_LOCATOR", "RETURN", "RETURNS", "REVOKE", "RIGHT", "ROLE", "ROLLBACK", "ROUND_CEILING",
			"ROUND_DOWN", "ROUND_FLOOR", "ROUND_HALF_DOWN", "ROUND_HALF_EVEN", "ROUND_HALF_UP", "ROUND_UP", "ROW", "ROWSET", "RUN", "SAVEPOINT",
			"SCHEMA", "SCRATCHPAD", "SECOND", "SECONDS", "SECQTY", "SECURITY", "SELECT", "SENSITIVE", "SESSION_USER", "SET",
			"SEQUENCE", "SIGNAL", "SIMPLE", "SNAN", "SOME", "SOURCE", "SPECIFIC", "STANDARD", "STATEMENT", "STATIC",
			"STAY", "STOGROUP", "STORE", "STYLE", "SUBPAGES", "SUMMARY", "SYNONYM", "SYSFUN", "SYSIBM", "SYSPROC",
			"SYSTEM", "TABLE", "TABLESPACE", "THEN", "TO", "TRIGGER", "TRUNCATE", "TYPE", "UNDO", "UNION",
			"UNIQUE", "UNTIL", "UPDATE", "USER", "USING", "VALIDPROC", "VALUE", "VALUES", "VARIABLE", "VARIANT",
			"VCAT", "VIEW", "VOLATILE", "VOLUMES", "WHEN", "WHENEVER", "WHERE", "WHILE", "WITH", "WLM",
			"XMLELEMENT", "XMLEXISTS", "XMLNAMESPACES", "XMLCAST", "YEAR", "YEARS"
		};

		// Token: 0x04004029 RID: 16425
		private static string[] ReservedWordsAS400 = new string[]
		{
			"ACTIVATE", "ADD", "ALIAS", "ALL", "ALLOCATE", "ALLOW", "ALTER", "AND", "ANY", "AS",
			"ASENSITIVE", "AT", "ATTRIBUTES", "AUTHORIZATION", "BEGIN", "BETWEEN", "BINARY", "BY", "CACHE", "CALL",
			"CALLED", "CARDINALITY", "CASE", "CAST", "CCSID", "CHAR", "CHARACTER", "CHECK", "CLOSE", "COLLECTION",
			"COLUMN", "COMMENT", "COMMIT", "CONCAT", "CONDITION", "CONNECT", "CONNECTION", "CONSTRAINT", "CONTAINS", "CONTINUE",
			"COUNT", "COUNT_BIG", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_PATH", "CURRENT_SCHEMA", "CURRENT_SERVER", "CURRENT_TIME",
			"CURRENT_TIMESTAMP", "CURRENT_TIMEZONE", "CURRENT_USER", "CURSOR", "CYCLE", "DATABASE", "DATAPARTITIONNAME", "DATAPARTITIONNUM", "DATE", "DAY",
			"DAYS", "DBINFO", "DBPARTITIONNAME", "DBPARTTIONNUM", "DEALLOCATE", "DECLARE", "DEFAULT", "DEFAULTS", "DEFINITION", "DELETE",
			"DENSE_RANK", "DENSERANK", "DESCRIBE", "DESCRIPTOR", "DETERMINISTIC", "DIAGNOSTICS", "DISABLE", "DISALLOW", "DISCONNECT", "DISTINCT",
			"DO", "DOUBLE", "DROP", "DYNAMIC", "EACH", "ELSE", "ELSEIF", "ENABLE", "ENCRYPTION", "END",
			"END-EXEC", "ENDING", "ESCAPE", "EVERY", "EXCEPT", "EXCEPTION", "EXCLUDING", "EXCLUSIVE", "EXECUTE", "EXISTS",
			"EXIT", "EXTERNAL", "EXTRACT", "FENCED", "FETCH", "FILE", "FINAL", "FOR", "FOREIGN", "FREE",
			"FROM", "FULL", "FUNCTION", "GENERAL", "GENERATED", "GET", "GLOBAL", "GO", "GOTO", "GRANT",
			"GRAPHIC", "GROUP", "HANDLER", "HASH", "HASHED_VALUE", "HAVING", "HINT", "HOLD", "HOUR", "HOURS",
			"IDENTITY", "IF", "IMMEDIATE", "IN", "INCLUDING", "INCLUSIVE", "INCREMENT", "INDEX", "INDICATOR", "INHERIT",
			"INNER", "INOUT", "INSENSITIVE", "INSERT", "INTEGRITY", "INTERSECT", "INTO", "IS", "ISOLATION", "ITERATE",
			"JAVA", "JOIN", "KEY", "LABEL", "LANGUAGE", "LATERAL", "LEAVE", "LEFT", "LIKE", "LINKTYPE",
			"LOCAL", "LOCALDATE", "LOCALTIME", "LOCALTIMESTAMP", "LOCK", "LONG", "LOOP", "MAINTAINED", "MATERIALIZED", "MAXVALUE",
			"MICROSECOND", "MICROSECONDS", "MINUTE", "MINUTES", "MINVALUE", "MODE", "MODIFIES", "MONTH", "MONTHS", "NEW",
			"NEW_TABLE", "NEXTVAL", "NO", "NOCACHE", "NOCYCLE", "NODENAME", "NODENUMBER", "NOMAXVALUE", "NOMINVALUE", "NOORDER",
			"NORMALIZED", "NOT", "NULL", "OF", "ON", "OPEN", "OPTIMIZE", "OPTION", "OR", "ORDER",
			"OUT", "OUTER", "OVER", "OVERRIDING", "PACKAGE", "PAGESIZE", "PARAMETER", "PART", "PARTITION", "PARTITIONING",
			"PARTITIONS", "PASSWORD", "PATH", "POSITION", "PREPARE", "PREVVAL", "PRIMARY", "PRIVILEGES", "PROCEDURE", "PROGRAM",
			"QUERY", "RANGE", "READ", "READS", "RECOVERY", "REFERENCES", "REFERENCING", "REFRESH", "RELEASE", "RENAME",
			"REPEAT", "RESET", "RESIGNAL", "RESTART", "RESULT", "RETURN", "RETURNS", "REVOKE", "RIGHT", "ROLLBACK",
			"ROUTINE", "ROW", "ROW_NUMBER", "ROWNUMBER", "ROWS", "RRN", "RUN", "SAVEPOINT", "SCHEMA", "SCRATCHPAD",
			"SCROLL", "SEARCH", "SECOND", "SECONDS", "SELECT", "SENSITIVE", "SEQUENCE", "SESSION", "SESSION_USER", "SET",
			"SIGNAL", "SIMPLE", "SOME", "SOURCE", "SPECIFIC", "SQL", "SQLID", "STACKED", "START", "STARTING",
			"STATEMENT", "STATIC", "SUBSTRING", "SUMMARY", "SYNONYM", "SYSTEM_USER", "TABLE", "THEN", "TIME", "TIMESTAMP",
			"TO", "TRANSACTION", "TRIGGER", "TRIM", "TYPE", "UNDO", "UNION", "UNIQUE", "UNTIL", "UPDATE",
			"USAGE", "USER", "USING", "VALUE", "VALUES", "VARIABLE", "VARIANT", "VERSION", "VIEW", "VOLATILE",
			"WHEN", "WHERE", "WHILE", "WITH", "WITHOUT", "WRITE", "YEAR", "YEARS"
		};

		// Token: 0x0400402A RID: 16426
		private static string[] ReservedWordsUDB = new string[]
		{
			"ABSOLUTE", "ACQUIRE", "ACTION", "ACTIVATE", "ADD", "AFTER", "ALL", "ALLOCATE", "ALLOW", "ALTER",
			"AND", "ANY", "AS", "ASENSITIVE", "ASSOCIATE", "ASUTIME", "AT", "ATTRIBUTES", "AUDIT", "AUTHORIZATION",
			"AUX", "AUXILIARY", "BEFORE", "BEGIN", "BETWEEN", "BINARY", "BUFFERPOOL", "BY", "CACHE", "CALL",
			"CALLED", "CAPTURE", "CARDINALITY", "CASCADED", "CASE", "CAST", "CCSID", "CHAR", "CHARACTER", "CHECK",
			"CLOSE", "CLUSTER", "COLLECTION", "COLLID", "COLUMN", "COMMENT", "COMMIT", "CONCAT", "CONDITION", "CONNECT",
			"CONNECTION", "CONSTRAINT", "CONTAINS", "CONTINUE", "COUNT", "COUNT_BIG", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE",
			"CURRENT_LC_TYPE", "CURRENT_PATH", "CURRENT_SCHEMA", "CURRENT_SERVER", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_TIMEZONE", "CURRENT_USER", "CURSOR", "CYCLE",
			"DATA", "DATABASE", "DATAPARTITIONNAME", "DATAPARTITIONNUM", "DATE", "DAY", "DAYS", "DB2GENERAL", "DB2GENERL", "DB2SQL",
			"DBINFO", "DBPARTITIONNAME", "DBPARTTIONNUM", "DEALLOCATE", "DECLARE", "DEFAULT", "DEFAULTS", "DEFINITION", "DELETE", "DENSE_RANK",
			"DENSERANK", "DESCRIBE", "DESCRIPTOR", "DETERMINISTIC", "DIAGNOSTICS", "DISABLE", "DISALLOW", "DISCONNECT", "DISTINCT", "DO",
			"DOUBLE", "DROP", "DSSIZE", "DYNAMIC", "EACH", "EDITPROC", "ELSE", "ELSEIF", "ENABLE", "ENCODING",
			"ENCRYPTION", "END", "END-EXEC", "ENDING", "ERASE", "ESCAPE", "EXCEPT", "EXCEPTION", "EXCLUDING", "EXCLUSIVE",
			"EXECUTE", "EXISTS", "EXIT", "EXPLAIN", "EXTERNAL", "EXTRACT", "FENCED", "FETCH", "FIELDPROC", "FILE",
			"FINAL", "FOR", "FOREIGN", "FREE", "FROM", "FULL", "FUNCTION", "GENERAL", "GENERATED", "GET",
			"GLOBAL", "GO", "GOTO", "GRANT", "GRAPHIC", "GROUP", "HANDLER", "HASH", "HASHED_VALUE", "HAVING",
			"HINT", "HOLD", "HOUR", "HOURS", "IDENTITY", "IF", "IMMEDIATE", "IN", "INCLUDING", "INCLUSIVE",
			"INCREMENT", "INDEX", "INDICATOR", "INHERIT", "INNER", "INOUT", "INSENSITIVE", "INSERT", "INTEGRITY", "INTERSECT",
			"INTO", "IS", "ISOBID", "ISOLATION", "ITERATE", "JAR", "JAVA", "JOIN", "KEY", "LABEL",
			"LANGUAGE", "LATERAL", "LC_TYPE", "LEAVE", "LEFT", "LIKE", "LINKTYPE", "LOCAL", "LOCALDATE", "LOCALE",
			"LOCALTIME", "LOCALTIMESTAMP", "LOCATOR", "LOCATORS", "LOCK", "LOCKMAX", "LOCKSIZE", "LONG", "LOOP", "MAINTAINED",
			"MATERIALIZED", "MAXVALUE", "MICROSECOND", "MICROSECONDS", "MINUTE", "MINUTES", "MINVALUE", "MODE", "MODIFIES", "MONTH",
			"MONTHS", "NEW", "NEW_TABLE", "NEXTVAL", "NO", "NOCACHE", "NOCYCLE", "NODENAME", "NODENUMBER", "NOMAXVALUE",
			"NOMINVALUE", "NONE", "NOORDER", "NORMALIZED", "NOT", "NULL", "NULLS", "NUMPARTS", "OBID", "OF",
			"OLD", "OLD_TABLE", "ON", "OPEN", "OPTIMIZATION", "OPTIMIZE", "OPTION", "OR", "ORDER", "OUT",
			"OUTER", "OVER", "OVERRIDING", "PACKAGE", "PADDED", "PAGESIZE", "PARAMTER", "PART", "PARTITION", "PARTITIONED",
			"PARTITIONING", "PARTITIONS", "PASSWORD", "PATH", "PIECESIZE", "PLAN", "POSITION", "PRECISION", "PREPARE", "PREVVAL",
			"PRIMARY", "PRIQTY", "PRIVILEGES", "PROCEDURE", "PROGRAM", "PSID", "QUERY", "QUERYNO", "RANGE", "RANK",
			"READ", "READS", "RECOVERY", "REFERENCES", "REFERENCING", "REFRESH", "RELEASE", "RENAME", "REPEAT", "RESET",
			"RESIGNAL", "RESTART", "RESTRICT", "RESULT", "RESULT_SET_LOCATOR", "RETURN", "RETURNS", "REVOKE", "RIGHT", "ROLLBACK",
			"ROUTINE", "ROW", "ROW_NUMBER", "ROWNUMBER", "ROWS", "ROWSET", "RRN", "RUN", "SAVEPOINT", "SCHEMA",
			"SCRATCHPAD", "SCROLL", "SEARCH", "SECOND", "SECONDS", "SECQTY", "SECURITY", "SELECT", "SENSITIVE", "SEQUENCE",
			"SESSION", "SESSION_USER", "SET", "SIGNAL", "SIMPLE", "SOME", "SOURCE", "SPECIFIC", "SQL", "SQLID",
			"STACKED", "STANDARD", "START", "STARTING", "STATEMENT", "STATIC", "STAY", "STOGROUP", "STORES", "STYLE",
			"SUBSTRING", "SUMMARY", "SYNONYM", "SYSFUN", "SYSIBM", "SYSPROC", "SYSTEM", "SYSTEM_USER", "TABLE", "TABLESPACE",
			"THEN", "TIME", "TIMESTAMP", "TO", "TRANSACTION", "TRIGGER", "TRIM", "TYPE", "UNDO", "UNION",
			"UNIQUE", "UNTIL", "UPDATE", "UPPER", "USAGE", "USER", "USING", "VALIDPROC", "VALUE", "VALUES",
			"VARIABLE", "VARIANT", "VCAT", "VERSION", "VIEW", "VOLATILE", "VOLUMES", "WHEN", "WHENEVER", "WHERE",
			"WHILE", "WITH", "WITHOUT", "WLM", "WRITE", "XMLELEMENT", "YEAR", "YEARS"
		};
	}
}
